wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712310278.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.10.13
      5: 0.16.6
      6: 4.38.2
      8:
      - 2
      - 5
      - 13
      13: linux-x86_64
encoder_name:
  desc: null
  value: resnet50
encoder_weights:
  desc: null
  value: imagenet
in_channels:
  desc: null
  value: 1
classes:
  desc: null
  value: 14
loss_fn:
  desc: null
  value: null
loss_function:
  desc: null
  value: DiceCELoss
learning_rate:
  desc: null
  value: 0.005
bilinear:
  desc: null
  value: false
