MODEL:
  ARCH: "Unet"
  ENCODER: "resnet50"
  ENCODER_WEIGHTS: "imagenet"
  NUM_CLASSES: 1
  MODE: "binary"
  ACT_FUNC: "sigmoid"
DATA:
  NAME: "retinal-lesions"
  DATA_ROOT: "./data/retinal-lesions-v20191227"
  RESIZE: [512,512]
  LABEL_VALUES: [127, 255]
  BINARY: True
  NUM_WORKERS: 8
LOSS:
  NAME: "DiceLoss"
SOLVER:
  OPTIMIZING_METHOD: "adam"
  BASE_LR: 0.0001
  MAX_EPOCH: 60
  # LR_POLICY: "cosine"
  LR_POLICY: "reduce_on_plateau"
  FACTOR: 0.5
  PATIENCE: 6
TRAIN:
  DATA_PATH: "train.txt"
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  CALCULATE_METRIC: True
  # AUTO_RESUME: True
VAL:
  DATA_PATH: "val.txt"
  BATCH_SIZE: 8
TEST:
  DATA_PATH: "test.txt"
  BATCH_SIZE: 8
  CHECKPOINT_PATH: ""
WANDB:
  ENABLE: True
  PROJECT: iccv2021
  ENTITY: newton
OUTPUT_DIR: ./log/retinal-lesions/unet_dice_512x512
RNG_SEED: 2
LOG_PERIOD: 30
DEVICE: "cuda:0"
PERFORM_TEST: True
