wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712257593.0
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      - 103
      3:
      - 7
      - 23
      4: 3.8.19
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
encoder_name:
  desc: null
  value: resnet50
encoder_weights:
  desc: null
  value: imagenet
in_channels:
  desc: null
  value: 1
classes:
  desc: null
  value: 14
loss_fn:
  desc: null
  value: null
loss_function:
  desc: null
  value: DiceCELoss
learning_rate:
  desc: null
  value: 0.005
bilinear:
  desc: null
  value: false
