wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712315261.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.6
      6: 4.38.2
      8:
      - 2
      - 5
      - 13
      13: linux-x86_64
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.06195695486077984
