wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712315463.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 10
      - 11
      - 12
      - 35
      - 41
      - 48
      - 49
      - 53
      - 55
      - 63
      - 71
      - 74
      - 80
      - 103
      - 105
      3:
      - 5
      - 7
      - 13
      - 23
      - 62
      4: 3.10.13
      5: 0.16.6
      6: 4.38.2
      8:
      - 2
      - 5
      - 13
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_accuracy_micro
      5: 1
      6:
      - 1
    - 1: val_accuracy_MACRO
      5: 1
      6:
      - 1
    - 1: val_F1
      5: 1
      6:
      - 1
    - 1: val_Dice
      5: 1
      6:
      - 1
    - 1: val_Jaccard
      5: 1
      6:
      - 1
    - 1: Predicted Images._type
      5: 1
      6:
      - 1
    - 1: Predicted Images.sha256
      5: 1
      6:
      - 1
    - 1: Predicted Images.size
      5: 1
      6:
      - 1
    - 1: Predicted Images.path
      5: 1
      6:
      - 1
    - 1: Predicted Images.format
      5: 1
      6:
      - 1
    - 1: Predicted Images.width
      5: 1
      6:
      - 1
    - 1: Predicted Images.height
      5: 1
      6:
      - 1
batch_size:
  desc: null
  value: 32
learning_rate:
  desc: null
  value: 0.025198961384678444
encoder_name:
  desc: null
  value: resnet50
encoder_weights:
  desc: null
  value: imagenet
in_channels:
  desc: null
  value: 1
classes:
  desc: null
  value: 14
loss_fn:
  desc: null
  value: null
loss_function:
  desc: null
  value: DiceCELoss
bilinear:
  desc: null
  value: false
